import { Avance } from './avance.interface';
import { Evidencia } from './evidencia.interface';

export interface Obra {
  id?: number;
  objeto?: string;
  montoInversion?: string;
  porcentajeInversion?: number;
  descripcionTipoInversion?: string;
  fechaContratacion?: Date;
  fechaEstimadaInicio?: Date;
  fechaEstimadaFin?: Date;
  latitud?: string;
  longitud?: string;
  idTipoObraSocial?: number;
  descripcionTipoObraSocial?: string;
  idTipoObra?: number;
  descripcionTipoObra?: string;
  comentarios?: string;
  porcentajeAvance?: number;
  fechaInicioEstimada?: Date;
  esCredito?: boolean;
  idTipoContrato?: number;
  descripcionTipoContrato?: string;
  fechaInicio?: Date;
  fechaFinalizacion?: Date;
  cct?: string;
  totalBeneficiados?: number;
  publicadoPor?: number;
  nombrePublicadoPor?: string;
  fechaHoraRegistro?: Date;
  modificadoPor?: null;
  nombreModificadoPor?: null;
  fechaModificacion?: null;
  idNivelEducativo?: number;
  descripcionNivelEducativo?: null;
  idTipoAnexo?: number;
  descripcionTipoAnexo?: null;
  idEjecutor?: number;
  descripcionEjecutor?: string;
  idTipoInversion?: number;
  idTipoModalidad?: number;
  descripcionTipoModalidad?: string;
  idDependencia?: number;
  descripcionDependencia?: string;
  idContratista?: number;
  descripcionContratista?: null;
  numeroContrato?: string;
  idSupervisor?: number;
  nombreSupervisor?: string;
  nombreMunicipio?: string;
  avances?: Avance[];
  documentos?: any[];
  evidencias?: Evidencia[];
}
