export enum ObrasEnums {
  EDIFICIOS_PUBLICOS = 'EDIFICIOS PÚBLICOS',
  INFRAESTRUCTURAS_URBANAS = 'INFRAESTRUCTURAS URBANAS',
  INFRAESTRUCTURAS_DE_TRANSPORTE = 'INFRAESTRUCTURAS DE TRANSPORTE',
  INFRAESTRUCTURAS_HIDRAULICAS = 'INFRAESTRUCTURAS HIDRÁULICAS',
  ELECTRIFICACION = 'ELECTRIFICACIÓN',
  REMODELACION_Y_CONSERVACION_INFRAESTRUCTURA = 'REMODELACIÓN Y CONSERVACIÓN INFRAESTRUCTURA',
  CONSTRUCCION_INFRAESTRUCTURA = 'CONSTRUCCIÓN INFRAESTRUCTURA',
  LIMPIEZA_MANTENIMIENTO = 'LIMPIEZA - MANTENIMIENTO',
  EDUCACIOIN = 'EDUCACIÓN',
  PAVIMENTACION = 'PAVIMENTACIÓN',
  REHABILITACION_DE_CAMINO = 'REHABILITACIÓN DE CAMINO',
  PUENTE = 'PUENTE',
  POZOS_DE_AGUA = 'POZOS DE AGUA',
  AGUA_POTABLE_Y_DRENAJE = 'AGUA POTABLE Y DRENAJE',
  DESAZOLVE = 'DESAZOLVE'
}
